### ISSUE TITLE
Override theme - hovered

### ISSUE THREAD

**Issue by rickswe** [956MB/vscode-dark-plus.yazi#1]
Hello,

I was wondering if there was a way to override the theme?
I can do it fine with dracula but not with your theme? This is my ~/.config/yazi/theme.toml.
When I change to dracula I can see the hovered in red. If I hard code hovered in the flavor.toml it works.

```toml
# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[flavor]
# dark = "dracula"
dark = "vscode-dark-plus"
# light = "vscode-dark-plus"

[manager]

symlink_target = { italic = true, bg = "black", fg = "lightcyan" }
hovered = { fg = "#1E1E1E", bg = "#CD3131" }
```

Thanks for the awesome theme.
